[#-- @ftlvariable name="repository" type="com.atlassian.bamboo.plugins.git.GitRepository" --]
[@ww.checkbox labelKey='repository.gerrit.useSubmodules' name='repository.gerrit.useSubmodules' /]
[@ww.textfield labelKey='repository.gerrit.commandTimeout' name='repository.gerrit.commandTimeout' /]
[@ww.checkbox labelKey='repository.gerrit.verbose.logs' name='repository.gerrit.verbose.logs' /]
[@ww.textfield labelKey='repository.gerrit.rebuildTimeout' name='repository.gerrit.rebuildTimeout' /]
